[[layer]]
name = "DEF"
keys = """
Tab Q W E R T Y U I O P Backspace
LCtrl A S D F G H J K L Semicolon Quote
LShift Z X C V B N M Comma Dot Slash RShift
LAlt Space Space Space Space Space Space Space Space Space RAlt Enter
_ _ _ _ _ _ _ _ _ _ _ _
"""
