[aliases]
BT = "TO(BT)"
Func = "MO(FUNC)"
Num = "MO(NUM)"
Mouse = "MO(MOUSE)"
N1 = "1"
N2 = "2"
N3 = "3"
N4 = "4"
N5 = "5"
N6 = "6"
N7 = "7"
N8 = "8"
N9 = "9"
N0 = "0"
LBracket = "LeftBracket"
RBracket = "RightBracket"
BT_Sel0 = "User0"
BT_Sel1 = "User1"
BT_Sel2 = "User2"
BT_Sel3 = "User3"
BT_Sel4 = "User4"
BT_Clr = "User10"
BT_ClrAll = "OutputBluetooth"
